version: 2
updates:
- package-ecosystem: bundler
  directory: "/"
  schedule:
    interval: daily
    timezone: Asia/Tokyo
  open-pull-requests-limit: 10
  ignore:
  - dependency-name: chartkick
    versions:
    - 4.0.0
    - 4.0.2
  - dependency-name: graphql
    versions:
    - 1.12.7
  - dependency-name: rspec-rails
    versions:
    - 4.1.0
  - dependency-name: rails
    versions:
    - 6.1.2.1
- package-ecosystem: npm
  directory: "/"
  schedule:
    interval: daily
    timezone: Asia/Tokyo
  open-pull-requests-limit: 10
  ignore:
  - dependency-name: chartkick
    versions:
    - 4.0.0
    - 4.0.2
  - dependency-name: chart.js
    versions:
    - 3.0.2
- package-ecosystem: docker
  directory: "/"
  schedule:
    interval: daily
    timezone: Asia/Tokyo
  open-pull-requests-limit: 10
  ignore:
  - dependency-name: ruby
    versions:
    - 3.0.0.pre.alpine3.12
- package-ecosystem: github-actions
  directory: "/"
  schedule:
    interval: daily
    timezone: Asia/Tokyo
  open-pull-requests-limit: 10
