version: "3.3"

services:
  app:
    build: .
    depends_on:
      - db
    networks:
      - backend
    ports:
      - 3000:3000
    volumes:
      - .:/app
    tty: true
    stdin_open: true
    command: ["bin/rails", "server", "-b", "0.0.0.0"]

  db:
    image: postgres:11.6-alpine
    volumes:
      - ./tmp/db:/var/lib/postgresql/data
    environment:
      POSTGRES_PASSWORD: password
      POSTGRES_USER: kakeibo
      POSTGRES_DB: kakeibo_development
    ports:
      - 5432:5432
    networks:
      - backend

networks:
  backend:
    driver: bridge
